skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hashpandas = "97c5ZbrrVVJa8jY1vVHX1tpKtZXrUBp7YyfpfhKnxpmK"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
